spring:
  application:
    name: personnel-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/Personnel
    username: postgres
    password: postgre

server:
  port: 8091